import Access_Profiles from "../../database/models/Access_Profiles.js";
import Action_Status from "../../database/models/Action_Status.js";
import Address_Types from "../../database/models/Address_Types.js";
import Addresses from "../../database/models/Addresses.js";
import Business_Units from "../../database/models/Business_Units.js";
import Cities from "../../database/models/Cities.js";
import Clients from "../../database/models/Clients.js";
import Collaborator_Contracts from "../../database/models/Collaborator_Contracts.js";
import Collaborator_Functions from "../../database/models/Collaborator_Functions.js";
import Collaborators from "../../database/models/Collaborators.js";
import Collaborators_X_Functions from "../../database/models/Collaborators_X_Functions.js";
import Companies from "../../database/models/Companies.js";
import Comparators from "../../database/models/Comparators.js";
import Condition_Items from "../../database/models/Condition_Items.js";
import Conditions from "../../database/models/Conditions.js";
import Connections from "../../database/models/Connections.js";
import Contact_Types from "../../database/models/Contact_Types.js";
import Contacts from "../../database/models/Contacts.js";
import Contexts from "../../database/models/Contexts.js";
import Continents from "../../database/models/Continents.js";
import Contract_Types from "../../database/models/Contract_Types.js";
import Countries from "../../database/models/Countries.js";
import Currencies from "../../database/models/Currencies.js";
import Data_Origins from "../../database/models/Data_Origins.js";
import Data_Types from "../../database/models/Data_Types.js";
import Entities_Types from "../../database/models/Entities_Types.js";
import Errors from "../../database/models/Errors.js";
import Financial_Value_Forms from "../../database/models/Financial_Value_Forms.js";
import Financial_Value_Localization_Types from "../../database/models/Financial_Value_Localization_Types.js";
import Financial_Value_Mov_Types from "../../database/models/Financial_Value_Mov_Types.js";
import Form_Types from "../../database/models/Form_Types.js";
import Greatnesses from "../../database/models/Greatnesses.js";
import Groups from "../../database/models/Groups.js";
import Groups_Items from "../../database/models/Groups_Items.js";
import Identifier_Types from "../../database/models/Identifier_Types.js";
import Languages from "../../database/models/Languages.js";
import Logs from "../../database/models/Logs.js";
import Measurement_Units from "../../database/models/Measurement_Units.js";
import Modules from "../../database/models/Modules.js";
import NeighborHoods from "../../database/models/NeighborHoods.js";
import Packagings from "../../database/models/Packagings.js";
import Parameter_Values from "../../database/models/Parameter_Values.js";
import Parameters from "../../database/models/Parameters.js";
import People from "../../database/models/People.js";
import People_Addresses from "../../database/models/People_Addresses.js";
import People_Contacts from "../../database/models/People_Contacts.js";
import Permissions from "../../database/models/Permissions.js";
import Postal_Codes from "../../database/models/Postal_Codes.js";
import Postal_Codes_Paths from "../../database/models/Postal_Codes_Paths.js";
import Postal_Codes_Streets from "../../database/models/Postal_Codes_Streets.js";
import Power_Types from "../../database/models/Power_Types.js";
import Processes from "../../database/models/Processes.js";
import Record_Status from "../../database/models/Record_Status.js";
import Relationship_Types from "../../database/models/Relationship_Types.js";
import Relationship_Values from "../../database/models/Relationship_Values.js";
import Relationships from "../../database/models/Relationships.js";
import Routine_Contents from "../../database/models/Routine_Contents.js";
import Routine_Types from "../../database/models/Routine_Types.js";
import Routines from "../../database/models/Routines.js";
import Run_Status from "../../database/models/Run_Status.js";
import Schemas from "../../database/models/Schemas.js";
import States from "../../database/models/States.js";
import Street_Types from "../../database/models/Street_Types.js";
import Streets from "../../database/models/Streets.js";
import Suppliers from "../../database/models/Suppliers.js";
import Sync_Status from "../../database/models/Sync_Status.js";
import Tables from "../../database/models/Tables.js";
import Texts from "../../database/models/Texts.js";
import Translates from "../../database/models/Translates.js";
import User_Profile_Timeworks from "../../database/models/User_Profile_Timeworks.js";
import User_Timeworks from "../../database/models/User_Timeworks.js";
import User_Tokens from "../../database/models/User_Tokens.js";
import Users from "../../database/models/Users.js";
import Value_Names from "../../database/models/Value_Names.js";
import Warehouse_Address_Capacities from "../../database/models/Warehouse_Address_Capacities.js";
import Warehouse_Address_Coordinates from "../../database/models/Warehouse_Address_Coordinates.js";
import Warehouse_Address_Dimensions from "../../database/models/Warehouse_Address_Dimensions.js";
import Warehouse_Address_Types from "../../database/models/Warehouse_Address_Types.js";
import Warehouse_Addresses from "../../database/models/Warehouse_Addresses.js";
import Warehouses from "../../database/models/Warehouses.js";
import Container_Types from '../../database/models/Container_Types.js';
import Container_Type_Dimensions from '../../database/models/Container_Type_Dimensions.js';
import Container_Type_Capacities from '../../database/models/Container_Type_Capacities.js';
import Gtin_Types from '../../database/models/Gtin_Types.js';
import Ncms from '../../database/models/Ncms.js';
import Item_Status from '../../database/models/Item_Status.js';
import Items from '../../database/models/Items.js';
import Lots from '../../database/models/Lots.js';
import Containers from '../../database/models/Containers.js';
import Items_Lots_Containers from '../../database/models/Items_Lots_Containers.js';
import Stock_Entities from '../../database/models/Stock_Entities.js';
import Stock_Entity_Relationship_Types from '../../database/models/Stock_Entity_Relationship_Types.js';
import Item_Stocks from '../../database/models/Item_Stocks.js';
import Item_Stock_Units from '../../database/models/Item_Stock_Units.js';
import Item_Meas_Pack_Identif from '../../database/models/Item_Meas_Pack_Identif.js';
import Movement_Types from '../../database/models/Movement_Types.js';
import Movement_Status from '../../database/models/Movement_Status.js';
import Conference_Types from '../../database/models/Conference_Types.js';
import Movements from '../../database/models/Movements.js';
import Movement_Groups from '../../database/models/Movement_Groups.js';
import Movements_Groups from '../../database/models/Movements_Groups.js';
import Movement_Entity_Relationship_Types from '../../database/models/Movement_Entity_Relationship_Types.js';
import Movements_Entities from '../../database/models/Movements_Entities.js';
import Movs_Items_Stocks from '../../database/models/Movs_Items_Stocks.js';
import Item_Mov_Amounts from '../../database/models/Item_Mov_Amounts.js';
import Item_Mov_Units from '../../database/models/Item_Mov_Units.js';
import Item_Mov_Amount_Restrictions from '../../database/models/Item_Mov_Amount_Restrictions.js';
import Item_Mov_Xml_Import_Id_Conversions from '../../database/models/Item_Mov_Xml_Import_Id_Conversions.js';
import Commission_Entitiy_Codes from '../../database/models/Commission_Entitiy_Codes.js';
import Commission_Items from '../../database/models/Commission_Items.js';
import Commission_Values from '../../database/models/Commission_Values.js';
import Objectives from '../../database/models/Objectives.js';
import Sql_Object_Types from '../../database/models/Sql_Object_Types.js';
import Sql_Processes from '../../database/models/Sql_Processes.js';
import Report_Visions from '../../database/models/Report_Visions.js';
import Sql_Objects from '../../database/models/Sql_Objects.js';
import Report_Data_Founts from '../../database/models/Report_Data_Founts.js';
import Report_Data_Fount_Items from '../../database/models/Report_Data_Fount_Items.js';
import Logistic_Mov_Types from '../../database/models/Logistic_Mov_Types.js';
import Logistic_Status from '../../database/models/Logistic_Status.js';
import Logistic_Reasons from '../../database/models/Logistic_Reasons.js';
import Logistic_Orders from '../../database/models/Logistic_Orders.js';
import Logistic_Orders_Movs from '../../database/models/Logistic_Orders_Movs.js';
import Logistic_Orders_Items_Mov_Amt from '../../database/models/Logistic_Orders_Items_Mov_Amt.js';
import Logistic_Orders_Movs_Received_Values from '../../database/models/Logistic_Orders_Movs_Received_Values.js';
import Logistic_Orders_Dest_Values from '../../database/models/Logistic_Orders_Dest_Values.js';
import Logistic_Logs from '../../database/models/Logistic_Logs.js';
import Projects_Items_Types from '../../database/models/Projects_Items_Types.js';
import Project_Item_Origin_Types from '../../database/models/Project_Item_Origin_Types.js';
import Projects_Items from '../../database/models/Projects_Items.js';
import Requirements_Types from '../../database/models/Requirements_Types.js';
import Requirements from '../../database/models/Requirements.js';
import Project_Task_Types from '../../database/models/Project_Task_Types.js';
import Project_Tasks from '../../database/models/Project_Tasks.js';
import Task_Status from '../../database/models/Task_Status.js';
import Tasks from '../../database/models/Tasks.js';
import Tasks_Status_Users from '../../database/models/Tasks_Status_Users.js';
import Tasks_Status_Users_Logs from '../../database/models/Tasks_Status_Users_Logs.js';
import Project_Tasks_Status_Users from '../../database/models/Project_Tasks_Status_Users.js';
import Campaigns from '../../database/models/Campaigns.js';
import Campaign_Kpis from '../../database/models/Campaign_Kpis.js';
import Campaign_Kpi_Value_Getters from '../../database/models/Campaign_Kpi_Value_Getters.js';
import Campaign_Kpi_Value_Periods from '../../database/models/Campaign_Kpi_Value_Periods.js';
import Campaign_Kpi_Arbitrary_Values from '../../database/models/Campaign_Kpi_Arbitrary_Values.js';
import Campaign_Kpi_Value_Details from '../../database/models/Campaign_Kpi_Value_Details.js';
import Campaign_Entities from '../../database/models/Campaign_Entities.js';
import Campaign_Kpi_Result_Values from '../../database/models/Campaign_Kpi_Result_Values.js';
import Campaign_Entities_Kpi_Result_Values from '../../database/models/Campaign_Entities_Kpi_Result_Values.js';
import Campaign_Kpi_Value_Detail_Entities from '../../database/models/Campaign_Kpi_Value_Detail_Entities.js';
import Apis from '../../database/models/Apis.js';
import Api_Requests from '../../database/models/Api_Requests.js';
import Api_Request_Calls from '../../database/models/Api_Request_Calls.js';
import Api_Responses from '../../database/models/Api_Responses.js';
import Maps_Api_Responses from '../../database/models/Maps_Api_Responses.js';
import PcAtivi from '../../database/models/winthor/PcAtivi.js';
import PcBairro from '../../database/models/winthor/PcBairro.js';
import PcCarreg from '../../database/models/winthor/PcCarreg.js';
import PcCidade from '../../database/models/winthor/PcCidade.js';
import PcClient from '../../database/models/winthor/PcClient.js';
import PcCob from '../../database/models/winthor/PcCob.js';
import PcConsum from '../../database/models/winthor/PcConsum.js';
import PcDepto from '../../database/models/winthor/PcDepto.js';
import PcDocEletronico from '../../database/models/winthor/PcDocEletronico.js';
import PcEmpr from '../../database/models/winthor/PcEmpr.js';
import PcEstado from '../../database/models/winthor/PcEstado.js';
import PcEstcr from '../../database/models/winthor/PcEstcr.js';
import PcFilial from '../../database/models/winthor/PcFilial.js';
import PcFornec from '../../database/models/winthor/PcFornec.js';
import PcNcm from '../../database/models/winthor/PcNcm.js';
import PcNfsaid from '../../database/models/winthor/PcNfsaid.js';
import PcPais from '../../database/models/winthor/PcPais.js';
import PcPixCobrancaDados from '../../database/models/winthor/PcPixCobrancaDados.js';
import PcPrest from '../../database/models/winthor/PcPrest.js';
import PcProdut from '../../database/models/winthor/PcProdut.js';
import PcRotaExp from '../../database/models/winthor/PcRotaExp.js';
import PcSuperv from '../../database/models/winthor/PcSuperv.js';
import PcTabDev from '../../database/models/winthor/PcTabDev.js';
import PcUsuari from '../../database/models/winthor/PcUsuari.js';
import PcVeicul from '../../database/models/winthor/PcVeicul.js';
import Produtos_Armazenados_Terceiros from '../../database/models/winthor/Produtos_Armazenados_Terceiros.js';
import SjdProduto_Origem from '../../database/models/sjd/SjdProduto_Origem.js';
import SjdTabpr_Origem from '../../database/models/sjd/SjdTabpr_Origem.js';
import SjdTabpr_Origem_Log from '../../database/models/sjd/SjdTabpr_Origem_Log.js';
import XMLBroker from '../../database/models/sjd/XMLBroker.js';
import EpAtividadesClientes from '../../database/models/ep/EpAtividadesClientes.js';
import EpCategoriasOrigem from '../../database/models/ep/EpCategoriasOrigem.js';
import EpCidades from '../../database/models/ep/EpCidades.js';
import EpClientes from '../../database/models/ep/EpClientes.js';
import EpDeparamentosProd from '../../database/models/ep/EpDeparamentosProd.js';
import EpEmpresas from '../../database/models/ep/EpEmpresas.js';
import EpFiliais from '../../database/models/ep/EpFiliais.js';
import EpFornecedores from '../../database/models/ep/EpFornecedores.js';
import EpMovimentacoesEnt from '../../database/models/ep/EpMovimentacoesEnt.js';
import EpMovimentacoesSaida from '../../database/models/ep/EpMovimentacoesSaida.js';
import EpNegociosOrigem from '../../database/models/ep/EpNegociosOrigem.js';
import EpNfsEnt from '../../database/models/ep/EpNfsEnt.js';
import EpNfsSaida from '../../database/models/ep/EpNfsSaida.js';
import EpOrigensInfo from '../../database/models/ep/EpOrigensInfo.js';
import EpPessoas from '../../database/models/ep/EpPessoas.js';
import EpPracasClientes from '../../database/models/ep/EpPracasClientes.js';
import EpProdutos from '../../database/models/ep/EpProdutos.js';
import EpRedesClientes from '../../database/models/ep/EpRedesClientes.js';
import EpRotasClientes from '../../database/models/ep/EpRotasClientes.js';
import EpTrabalhadores from '../../database/models/ep/EpTrabalhadores.js';
import EpVendedores from '../../database/models/ep/EpVendedores.js';


import Error_Logs from '../../database/models/winthor_integration/Error_Logs.js'
import Integration_Columns from '../../database/models/winthor_integration/Integration_Columns.js'
import Integration_Control from '../../database/models/winthor_integration/Integration_Control.js'
import Integration_Parameters from '../../database/models/winthor_integration/Integration_Parameters.js'
import Integration_Tables from '../../database/models/winthor_integration/Integration_Tables.js'
import Businesses from '../../database/models/external_data/Businesses.js'
import ExternalDatasCities from '../../database/models/external_data/Cities.js'
import Cnaes from '../../database/models/external_data/Cnaes.js'
import ExternalDatasCountries from '../../database/models/external_data/Countries.js'
import Establishments from '../../database/models/external_data/Establishments.js'
import Legal_Natures from '../../database/models/external_data/Legal_Natures.js'
import Reasons from '../../database/models/external_data/Reasons.js'
import Responsible_Person_Qualifications from '../../database/models/external_data/Responsible_Person_Qualifications.js'
import Utils from "../utils/Utils.js";


export default class ModelsController {
    static async initModels(){
        Errors.initModel();
        Logs.initModel();
        Tables.initModel();
        Connections.initModel();
        Schemas.initModel();
        Contexts.initModel();
        Entities_Types.initModel();
        Data_Types.initModel();
        Action_Status.initModel();
        Parameters.initModel();
        Parameter_Values.initModel();
        Data_Origins.initModel();
        Record_Status.initModel();
        Sync_Status.initModel();
        Run_Status.initModel();
        Identifier_Types.initModel();
        Greatnesses.initModel();
        Measurement_Units.initModel();
        People.initModel();
        Collaborators.initModel();
        Access_Profiles.initModel();
        Users.initModel();
        User_Tokens.initModel();
        User_Profile_Timeworks.initModel();
        User_Timeworks.initModel();
        Processes.initModel();
        Routine_Types.initModel();
        Modules.initModel();
        Routines.initModel();
        Routine_Contents.initModel();
        Languages.initModel();
        Texts.initModel();
        Translates.initModel();
        Relationship_Types.initModel();
        Relationships.initModel();
        Value_Names.initModel();
        Relationship_Values.initModel();
        Comparators.initModel();
        Contract_Types.initModel();
        Currencies.initModel();
        Form_Types.initModel();
        Financial_Value_Forms.initModel();
        Financial_Value_Localization_Types.initModel();
        Financial_Value_Mov_Types.initModel();
        Continents.initModel();
        Countries.initModel();
        States.initModel();
        Cities.initModel();
        NeighborHoods.initModel();
        Street_Types.initModel();
        Streets.initModel();
        Address_Types.initModel();
        Postal_Codes.initModel();
        Postal_Codes_Streets.initModel();
        Postal_Codes_Paths.initModel();
        Addresses.initModel();
        Contact_Types.initModel();
        Contacts.initModel();
        People_Addresses.initModel();
        People_Contacts.initModel();
        Companies.initModel();
        Business_Units.initModel();
        Warehouses.initModel();
        Warehouse_Address_Types.initModel();
        Warehouse_Addresses.initModel();
        Warehouse_Address_Coordinates.initModel();
        Warehouse_Address_Dimensions.initModel();
        Warehouse_Address_Capacities.initModel();
        Clients.initModel();
        Suppliers.initModel();
        Collaborator_Functions.initModel();
        Collaborator_Contracts.initModel();
        Collaborators_X_Functions.initModel();
        Power_Types.initModel();
        Permissions.initModel();
        Conditions.initModel();
        Condition_Items.initModel();
        Groups.initModel();
        Groups_Items.initModel();
        Packagings.initModel();
        Container_Types.initModel();
        Container_Type_Dimensions.initModel();
        Container_Type_Capacities.initModel();
        Gtin_Types.initModel();
        Ncms.initModel();
        Item_Status.initModel();
        Items.initModel();
        Lots.initModel();
        Containers.initModel();
        Items_Lots_Containers.initModel();
        Stock_Entities.initModel();
        Stock_Entity_Relationship_Types.initModel();
        Item_Stocks.initModel();
        Item_Stock_Units.initModel();
        Item_Meas_Pack_Identif.initModel();
        Movement_Types.initModel();
        Movement_Status.initModel();
        Conference_Types.initModel();
        Movements.initModel();
        Movement_Groups.initModel();
        Movements_Groups.initModel();
        Movement_Entity_Relationship_Types.initModel();
        Movements_Entities.initModel();
        Movs_Items_Stocks.initModel();
        Item_Mov_Amounts.initModel();
        Item_Mov_Units.initModel();
        Item_Mov_Amount_Restrictions.initModel();
        Item_Mov_Xml_Import_Id_Conversions.initModel();
        Commission_Entitiy_Codes.initModel();
        Commission_Items.initModel();
        Commission_Values.initModel();
        Objectives.initModel();
        Sql_Object_Types.initModel();
        Sql_Processes.initModel();
        Report_Visions.initModel();
        Sql_Objects.initModel();
        Report_Data_Founts.initModel();
        Report_Data_Fount_Items.initModel();
        Logistic_Mov_Types.initModel();
        Logistic_Status.initModel();
        Logistic_Reasons.initModel();
        Logistic_Orders.initModel();
        Logistic_Orders_Movs.initModel();
        Logistic_Orders_Items_Mov_Amt.initModel();
        Logistic_Orders_Movs_Received_Values.initModel();
        Logistic_Orders_Dest_Values.initModel();
        Logistic_Logs.initModel();
        Projects_Items_Types.initModel();
        Project_Item_Origin_Types.initModel();
        Projects_Items.initModel();
        Requirements_Types.initModel();
        Requirements.initModel();
        Project_Task_Types.initModel();
        Project_Tasks.initModel();
        Task_Status.initModel();
        Tasks.initModel();
        Tasks_Status_Users.initModel();
        Tasks_Status_Users_Logs.initModel();
        Project_Tasks_Status_Users.initModel();
        Campaigns.initModel();
        Campaign_Kpis.initModel();
        Campaign_Kpi_Value_Getters.initModel();
        Campaign_Kpi_Value_Periods.initModel();
        Campaign_Kpi_Arbitrary_Values.initModel();
        Campaign_Kpi_Value_Details.initModel();
        Campaign_Entities.initModel();
        Campaign_Kpi_Result_Values.initModel();
        Campaign_Entities_Kpi_Result_Values.initModel();
        Campaign_Kpi_Value_Detail_Entities.initModel();
        Apis.initModel();
        Api_Requests.initModel();
        Api_Request_Calls.initModel();
        Api_Responses.initModel();
        Maps_Api_Responses.initModel();

        if (Utils.toBool(process.env.HAS_DB_EXTERNAL_DATA) == true) {
            Businesses.initModel();
            ExternalDatasCities.initModel();
            Cnaes.initModel();
            Countries.initModel();
            ExternalDatasCountries.initModel();
            Legal_Natures.initModel();
            Reasons.initModel();
            Responsible_Person_Qualifications.initModel();
        }
        
        if (Utils.toBool(process.env.HAS_WINTHOR_INTEGRATION) == true) {
            PcAtivi.initModel();
            PcBairro.initModel();
            PcCarreg.initModel();
            PcCidade.initModel();
            PcClient.initModel();
            PcCob.initModel();
            PcConsum.initModel();
            PcDepto.initModel();
            PcDocEletronico.initModel();
            PcEmpr.initModel();
            PcEstado.initModel();
            PcEstcr.initModel();
            PcFilial.initModel();
            PcFornec.initModel();
            PcNcm.initModel();
            PcNfsaid.initModel();
            PcPais.initModel();
            PcPixCobrancaDados.initModel();
            PcPrest.initModel();
            PcProdut.initModel();
            PcRotaExp.initModel();
            PcSuperv.initModel();
            PcTabDev.initModel();
            PcUsuari.initModel();
            PcVeicul.initModel();
            Produtos_Armazenados_Terceiros.initModel();
            Error_Logs.initModel();
            Integration_Columns.initModel();
            Integration_Control.initModel();
            Integration_Parameters.initModel();
            Integration_Tables.initModel();
        }

        if (Utils.toBool(process.env.HAS_CONSULT_INTEGRATION) == true) {
            SjdProduto_Origem.initModel();
            SjdTabpr_Origem.initModel();
            SjdTabpr_Origem_Log.initModel();
            XMLBroker.initModel();
        }

        if (Utils.toBool(process.env.HAS_EP_INTEGRATION) == true) {
            EpAtividadesClientes.initModel();
            EpCategoriasOrigem.initModel();
            EpCidades.initModel();
            EpClientes.initModel();
            EpDeparamentosProd.initModel();
            EpEmpresas.initModel();
            EpFiliais.initModel();
            EpFornecedores.initModel();
            EpMovimentacoesEnt.initModel();
            EpMovimentacoesSaida.initModel();
            EpNegociosOrigem.initModel();
            EpNfsEnt.initModel();
            EpNfsSaida.initModel();
            EpOrigensInfo.initModel();
            EpPessoas.initModel();
            EpPracasClientes.initModel();
            EpProdutos.initModel();
            EpRedesClientes.initModel();
            EpRotasClientes.initModel();
            EpTrabalhadores.initModel();
            EpVendedores.initModel();
        }
        
        

        await this.initAssociations();
    }

    static async initAssociations() {
        await Errors.initAssociations();
        await Logs.initAssociations();
        await Tables.initAssociations();
        await Connections.initAssociations();
        await Schemas.initAssociations();
        await Contexts.initAssociations();
        await Entities_Types.initAssociations();
        await Data_Types.initAssociations();
        await Action_Status.initAssociations();
        await Parameters.initAssociations();
        await Parameter_Values.initAssociations();
        await Data_Origins.initAssociations();
        await Record_Status.initAssociations();
        await Sync_Status.initAssociations();
        await Run_Status.initAssociations();
        await Identifier_Types.initAssociations();
        await Greatnesses.initAssociations();
        await Measurement_Units.initAssociations();
        await People.initAssociations();
        await Collaborators.initAssociations();
        await Access_Profiles.initAssociations();
        await Users.initAssociations();
        await User_Tokens.initAssociations();
        await User_Profile_Timeworks.initAssociations();
        await User_Timeworks.initAssociations();
        await Processes.initAssociations();
        await Routine_Types.initAssociations();
        await Modules.initAssociations();
        await Routines.initAssociations();
        await Routine_Contents.initAssociations();
        await Languages.initAssociations();
        await Texts.initAssociations();
        await Translates.initAssociations();
        await Relationship_Types.initAssociations();
        await Relationships.initAssociations();
        await Value_Names.initAssociations();
        await Relationship_Values.initAssociations();
        await Comparators.initAssociations();
        await Contract_Types.initAssociations();
        await Currencies.initAssociations();
        await Form_Types.initAssociations();
        await Financial_Value_Forms.initAssociations();
        await Financial_Value_Localization_Types.initAssociations();
        await Financial_Value_Mov_Types.initAssociations();
        await Continents.initAssociations();
        await Countries.initAssociations();
        await States.initAssociations();
        await Cities.initAssociations();
        await NeighborHoods.initAssociations();
        await Street_Types.initAssociations();
        await Streets.initAssociations();
        await Address_Types.initAssociations();
        await Postal_Codes.initAssociations();
        await Postal_Codes_Streets.initAssociations();
        await Postal_Codes_Paths.initAssociations();
        await Addresses.initAssociations();
        await Contact_Types.initAssociations();
        await Contacts.initAssociations();
        await People_Addresses.initAssociations();
        await People_Contacts.initAssociations();
        await Companies.initAssociations();
        await Business_Units.initAssociations();
        await Warehouses.initAssociations();
        await Warehouse_Address_Types.initAssociations();
        await Warehouse_Addresses.initAssociations();
        await Warehouse_Address_Coordinates.initAssociations();
        await Warehouse_Address_Dimensions.initAssociations();
        await Warehouse_Address_Capacities.initAssociations();
        await Clients.initAssociations();
        await Suppliers.initAssociations();
        await Collaborator_Functions.initAssociations();
        await Collaborator_Contracts.initAssociations();
        await Collaborators_X_Functions.initAssociations();
        await Power_Types.initAssociations();
        await Permissions.initAssociations();
        await Conditions.initAssociations();
        await Condition_Items.initAssociations();
        await Groups.initAssociations();
        await Groups_Items.initAssociations();
        await Packagings.initAssociations();
        await Container_Types.initAssociations();
        await Container_Type_Dimensions.initAssociations();
        await Container_Type_Capacities.initAssociations();
        await Gtin_Types.initAssociations();
        await Ncms.initAssociations();
        await Item_Status.initAssociations();
        await Items.initAssociations();
        await Lots.initAssociations();
        await Containers.initAssociations();
        await Items_Lots_Containers.initAssociations();
        await Stock_Entities.initAssociations();
        await Stock_Entity_Relationship_Types.initAssociations();
        await Item_Stocks.initAssociations();
        await Item_Stock_Units.initAssociations();
        await Item_Meas_Pack_Identif.initAssociations();
        await Movement_Types.initAssociations();
        await Movement_Status.initAssociations();
        await Conference_Types.initAssociations();
        await Movements.initAssociations();
        await Movement_Groups.initAssociations();
        await Movements_Groups.initAssociations();
        await Movement_Entity_Relationship_Types.initAssociations();
        await Movements_Entities.initAssociations();
        await Movs_Items_Stocks.initAssociations();
        await Item_Mov_Amounts.initAssociations();
        await Item_Mov_Units.initAssociations();
        await Item_Mov_Amount_Restrictions.initAssociations();
        await Item_Mov_Xml_Import_Id_Conversions.initAssociations();
        await Commission_Entitiy_Codes.initAssociations();
        await Commission_Items.initAssociations();
        await Commission_Values.initAssociations();
        await Objectives.initAssociations();
        await Sql_Object_Types.initAssociations();
        await Sql_Processes.initAssociations();
        await Report_Visions.initAssociations();
        await Sql_Objects.initAssociations();
        await Report_Data_Founts.initAssociations();
        await Report_Data_Fount_Items.initAssociations();
        await Logistic_Mov_Types.initAssociations();
        await Logistic_Status.initAssociations();
        await Logistic_Reasons.initAssociations();
        await Logistic_Orders.initAssociations();
        await Logistic_Orders_Movs.initAssociations();
        await Logistic_Orders_Items_Mov_Amt.initAssociations();
        await Logistic_Orders_Movs_Received_Values.initAssociations();
        await Logistic_Orders_Dest_Values.initAssociations();
        await Logistic_Logs.initAssociations();
        await Projects_Items_Types.initAssociations();
        await Project_Item_Origin_Types.initAssociations();
        await Projects_Items.initAssociations();
        await Requirements_Types.initAssociations();
        await Requirements.initAssociations();
        await Project_Task_Types.initAssociations();
        await Project_Tasks.initAssociations();
        await Task_Status.initAssociations();
        await Tasks.initAssociations();
        await Tasks_Status_Users.initAssociations();
        await Tasks_Status_Users_Logs.initAssociations();
        await Project_Tasks_Status_Users.initAssociations();
        await Campaigns.initAssociations();
        await Campaign_Kpis.initAssociations();
        await Campaign_Kpi_Value_Getters.initAssociations();
        await Campaign_Kpi_Value_Periods.initAssociations();
        await Campaign_Kpi_Arbitrary_Values.initAssociations();
        await Campaign_Kpi_Value_Details.initAssociations();
        await Campaign_Entities.initAssociations();
        await Campaign_Kpi_Result_Values.initAssociations();
        await Campaign_Entities_Kpi_Result_Values.initAssociations();
        await Campaign_Kpi_Value_Detail_Entities.initAssociations();
        await Apis.initAssociations();
        await Api_Requests.initAssociations();
        await Api_Request_Calls.initAssociations();
        await Api_Responses.initAssociations();
        await Maps_Api_Responses.initAssociations();

        if (Utils.toBool(process.env.HAS_DB_EXTERNAL_DATA) == true) {
            await Businesses.initAssociations();
            await ExternalDatasCities.initAssociations();
            await Cnaes.initAssociations();
            await ExternalDatasCountries.initAssociations();
            await Establishments.initAssociations();
            await Legal_Natures.initAssociations();
            await Reasons.initAssociations();
            await Responsible_Person_Qualifications.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_WINTHOR_INTEGRATION) == true) {        
            await PcAtivi.initAssociations();
            await PcBairro.initAssociations();
            await PcCarreg.initAssociations();
            await PcCidade.initAssociations();
            await PcClient.initAssociations();
            await PcCob.initAssociations();
            await PcConsum.initAssociations();
            await PcDepto.initAssociations();
            await PcDocEletronico.initAssociations();
            await PcEmpr.initAssociations();
            await PcEstado.initAssociations();
            await PcEstcr.initAssociations();
            await PcFilial.initAssociations();
            await PcFornec.initAssociations();
            await PcNcm.initAssociations();
            await PcNfsaid.initAssociations();
            await PcPais.initAssociations();
            await PcPixCobrancaDados.initAssociations();
            await PcPrest.initAssociations();
            await PcProdut.initAssociations();
            await PcRotaExp.initAssociations();
            await PcSuperv.initAssociations();
            await PcTabDev.initAssociations();
            await PcUsuari.initAssociations();
            await PcVeicul.initAssociations();
            await Produtos_Armazenados_Terceiros.initAssociations();
            await Error_Logs.initAssociations();
            await Integration_Columns.initAssociations();
            await Integration_Control.initAssociations();
            await Integration_Parameters.initAssociations();
            await Integration_Tables.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_CONSULT_INTEGRATION) == true) {
            await SjdProduto_Origem.initAssociations();
            await SjdTabpr_Origem.initAssociations();
            await SjdTabpr_Origem_Log.initAssociations();
            await XMLBroker.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_EP_INTEGRATION) == true) {
            await EpAtividadesClientes.initAssociations();
            await EpCategoriasOrigem.initAssociations();
            await EpCidades.initAssociations();
            await EpClientes.initAssociations();
            await EpDeparamentosProd.initAssociations();
            await EpEmpresas.initAssociations();
            await EpFiliais.initAssociations();
            await EpFornecedores.initAssociations();
            await EpMovimentacoesEnt.initAssociations();
            await EpMovimentacoesSaida.initAssociations();
            await EpNegociosOrigem.initAssociations();
            await EpNfsEnt.initAssociations();
            await EpNfsSaida.initAssociations();
            await EpOrigensInfo.initAssociations();
            await EpPessoas.initAssociations();
            await EpPracasClientes.initAssociations();
            await EpProdutos.initAssociations();
            await EpRedesClientes.initAssociations();
            await EpRotasClientes.initAssociations();
            await EpTrabalhadores.initAssociations();
            await EpVendedores.initAssociations();
        }
    }
}