//console.log('INIT MODELSCONTROLLER FILE');
//console.log('INIT MODELSCONTROLLER IMPORTS');

/*
* KEEP SAME ORDER IN THIS INPORTS OF MIGRATIONS FOLDER, MODELS CAN BE CONTAIN STATIC INITIALIZAR BLOCK WICH DEPPEND THIS ORDER TO INITIALIZE CORRECTLY
* if is necessary change order of migrations, then change the same order of import here
*/

/*DEFAULT TABLE MODELS*/
import Errors from "../../database/models/Errors.js";
import Logs from "../../database/models/Logs.js";
import Tables from "../../database/models/Tables.js";
import Connections from "../../database/models/Connections.js";
import Schemas from "../../database/models/Schemas.js";
import Contexts from "../../database/models/Contexts.js";
import Entities_Types from "../../database/models/Entities_Types.js";
import Data_Types from "../../database/models/Data_Types.js";
import Action_Status from "../../database/models/Action_Status.js";
import Parameters from "../../database/models/Parameters.js";
import Parameter_Values from "../../database/models/Parameter_Values.js";
import Data_Origins from "../../database/models/Data_Origins.js";
import Record_Status from "../../database/models/Record_Status.js";
import Sync_Status from "../../database/models/Sync_Status.js";
import Run_Status from "../../database/models/Run_Status.js";
import Identifier_Types from "../../database/models/Identifier_Types.js";
import Greatnesses from "../../database/models/Greatnesses.js";
import Measurement_Units from "../../database/models/Measurement_Units.js";
import People from "../../database/models/People.js";
import Collaborators from "../../database/models/Collaborators.js";
import Access_Profiles from "../../database/models/Access_Profiles.js";
import Users from "../../database/models/Users.js";
import User_Tokens from "../../database/models/User_Tokens.js";
import User_Profile_Timeworks from "../../database/models/User_Profile_Timeworks.js";
import User_Timeworks from "../../database/models/User_Timeworks.js";
import Processes from "../../database/models/Processes.js";
import Routine_Types from "../../database/models/Routine_Types.js";
import Modules from "../../database/models/Modules.js";
import Routines from "../../database/models/Routines.js";
import Routine_Contents from "../../database/models/Routine_Contents.js";
import Languages from "../../database/models/Languages.js";
import Texts from "../../database/models/Texts.js";
import Translates from "../../database/models/Translates.js";
import Relationship_Types from "../../database/models/Relationship_Types.js";
import Relationships from "../../database/models/Relationships.js";
import Value_Names from "../../database/models/Value_Names.js";
import Relationship_Values from "../../database/models/Relationship_Values.js";
import Lists_Names from "../../database/models/Lists_Names.js";
import Comparators from "../../database/models/Comparators.js";
import Contract_Types from "../../database/models/Contract_Types.js";
import Currencies from "../../database/models/Currencies.js";
import Form_Types from "../../database/models/Form_Types.js";
import Financial_Value_Forms from "../../database/models/Financial_Value_Forms.js";
import Financial_Value_Localization_Types from "../../database/models/Financial_Value_Localization_Types.js";
import Financial_Value_Mov_Types from "../../database/models/Financial_Value_Mov_Types.js";
import Continents from "../../database/models/Continents.js";
import Countries from "../../database/models/Countries.js";
import States from "../../database/models/States.js";
import Cities from "../../database/models/Cities.js";
import NeighborHoods from "../../database/models/NeighborHoods.js";
import Street_Types from "../../database/models/Street_Types.js";
import Streets from "../../database/models/Streets.js";
import Address_Types from "../../database/models/Address_Types.js";
import Postal_Codes from "../../database/models/Postal_Codes.js";
import Postal_Codes_Streets from "../../database/models/Postal_Codes_Streets.js";
import Postal_Codes_Paths from "../../database/models/Postal_Codes_Paths.js";
import Addresses from "../../database/models/Addresses.js";
import Contact_Types from "../../database/models/Contact_Types.js";
import Contacts from "../../database/models/Contacts.js";
import People_Addresses from "../../database/models/People_Addresses.js";
import People_Contacts from "../../database/models/People_Contacts.js";
import Companies from "../../database/models/Companies.js";
import Business_Units from "../../database/models/Business_Units.js";
import Warehouses from "../../database/models/Warehouses.js";
import Warehouse_Address_Types from "../../database/models/Warehouse_Address_Types.js";
import Warehouse_Addresses from "../../database/models/Warehouse_Addresses.js";
import Warehouse_Address_Coordinates from "../../database/models/Warehouse_Address_Coordinates.js";
import Warehouse_Address_Dimensions from "../../database/models/Warehouse_Address_Dimensions.js";
import Warehouse_Address_Capacities from "../../database/models/Warehouse_Address_Capacities.js";
import Clients from "../../database/models/Clients.js";
import Suppliers from "../../database/models/Suppliers.js";
import Collaborator_Functions from "../../database/models/Collaborator_Functions.js";
import Collaborator_Contracts from "../../database/models/Collaborator_Contracts.js";
import Collaborators_X_Functions from "../../database/models/Collaborators_X_Functions.js";
import Power_Types from "../../database/models/Power_Types.js";
import Permissions from "../../database/models/Permissions.js";
import Conditions from "../../database/models/Conditions.js";
import Condition_Items from "../../database/models/Condition_Items.js";
import Groups from "../../database/models/Groups.js";
import Groups_Items from "../../database/models/Groups_Items.js";
import Packagings from "../../database/models/Packagings.js";
import Container_Types from '../../database/models/Container_Types.js';
import Container_Type_Dimensions from '../../database/models/Container_Type_Dimensions.js';
import Container_Type_Capacities from '../../database/models/Container_Type_Capacities.js';
import Gtin_Types from '../../database/models/Gtin_Types.js';
import Ncms from '../../database/models/Ncms.js';
import Item_Status from '../../database/models/Item_Status.js';
import Items from '../../database/models/Items.js';
import Lots from '../../database/models/Lots.js';
import Containers from '../../database/models/Containers.js';
import Items_Lots_Containers from '../../database/models/Items_Lots_Containers.js';
import Stock_Entities from '../../database/models/Stock_Entities.js';
import Stock_Entity_Relationship_Types from '../../database/models/Stock_Entity_Relationship_Types.js';
import Item_Stocks from '../../database/models/Item_Stocks.js';
import Item_Stock_Units from '../../database/models/Item_Stock_Units.js';
import Item_Meas_Pack_Identif from '../../database/models/Item_Meas_Pack_Identif.js';
import Movement_Types from '../../database/models/Movement_Types.js';
import Movement_Status from '../../database/models/Movement_Status.js';
import Conference_Types from '../../database/models/Conference_Types.js';
import Movements from '../../database/models/Movements.js';
import Movement_Groups from '../../database/models/Movement_Groups.js';
import Movements_Groups from '../../database/models/Movements_Groups.js';
import Movement_Entity_Relationship_Types from '../../database/models/Movement_Entity_Relationship_Types.js';
import Movements_Entities from '../../database/models/Movements_Entities.js';
import Movs_Items_Stocks from '../../database/models/Movs_Items_Stocks.js';
import Item_Mov_Amounts from '../../database/models/Item_Mov_Amounts.js';
import Item_Mov_Units from '../../database/models/Item_Mov_Units.js';
import Item_Mov_Amount_Restrictions from '../../database/models/Item_Mov_Amount_Restrictions.js';
import Item_Mov_Xml_Import_Id_Conversions from '../../database/models/Item_Mov_Xml_Import_Id_Conversions.js';
import Commission_Entitiy_Codes from '../../database/models/Commission_Entitiy_Codes.js';
import Commission_Items from '../../database/models/Commission_Items.js';
import Commission_Values from '../../database/models/Commission_Values.js';
import Objectives from '../../database/models/Objectives.js';
import Sql_Object_Types from '../../database/models/Sql_Object_Types.js';
import Sql_Processes from '../../database/models/Sql_Processes.js';
import Report_Visions from '../../database/models/Report_Visions.js';
import Sql_Objects from '../../database/models/Sql_Objects.js';
import Report_Data_Founts from '../../database/models/Report_Data_Founts.js';
import Report_Data_Fount_Items from '../../database/models/Report_Data_Fount_Items.js';
import Logistic_Mov_Types from '../../database/models/Logistic_Mov_Types.js';
import Logistic_Status from '../../database/models/Logistic_Status.js';
import Logistic_Reasons from '../../database/models/Logistic_Reasons.js';
import Logistic_Orders from '../../database/models/Logistic_Orders.js';
import Logistic_Orders_Movs from '../../database/models/Logistic_Orders_Movs.js';
import Logistic_Orders_Items_Mov_Amt from '../../database/models/Logistic_Orders_Items_Mov_Amt.js';
import Logistic_Orders_Movs_Received_Values from '../../database/models/Logistic_Orders_Movs_Received_Values.js';
import Logistic_Orders_Dest_Values from '../../database/models/Logistic_Orders_Dest_Values.js';
import Logistic_Logs from '../../database/models/Logistic_Logs.js';
import Projects_Items_Types from '../../database/models/Projects_Items_Types.js';
import Project_Item_Origin_Types from '../../database/models/Project_Item_Origin_Types.js';
import Projects_Items from '../../database/models/Projects_Items.js';
import Requirements_Types from '../../database/models/Requirements_Types.js';
import Requirements from '../../database/models/Requirements.js';
import Project_Task_Types from '../../database/models/Project_Task_Types.js';
import Project_Tasks from '../../database/models/Project_Tasks.js';
import Task_Status from '../../database/models/Task_Status.js';
import Tasks from '../../database/models/Tasks.js';
import Tasks_Status_Users from '../../database/models/Tasks_Status_Users.js';
import Tasks_Status_Users_Logs from '../../database/models/Tasks_Status_Users_Logs.js';
import Project_Tasks_Status_Users from '../../database/models/Project_Tasks_Status_Users.js';
import Campaigns from '../../database/models/Campaigns.js';
import Campaign_Entities from '../../database/models/Campaign_Entities.js';
import Campaign_Kpis from '../../database/models/Campaign_Kpis.js';
import Campaign_Kpi_Value_Getters from '../../database/models/Campaign_Kpi_Value_Getters.js';
import Campaign_Kpi_Value_Details from '../../database/models/Campaign_Kpi_Value_Details.js';
import Campaign_Kpi_Result_Values from '../../database/models/Campaign_Kpi_Result_Values.js';
import Campaign_Kpi_Value_Detail_Entities from '../../database/models/Campaign_Kpi_Value_Detail_Entities.js';
import Campaign_Entities_Kpi_Value_Getters_Values from '../../database/models/Campaign_Entities_Kpi_Value_Getters_Values.js';
import Campaign_Entities_Kpi_Result_Values from '../../database/models/Campaign_Entities_Kpi_Result_Values.js';
import Apis from '../../database/models/Apis.js';
import Api_Requests from '../../database/models/Api_Requests.js';
import Api_Request_Calls from '../../database/models/Api_Request_Calls.js';
import Api_Responses from '../../database/models/Api_Responses.js';
import Maps_Api_Responses from '../../database/models/Maps_Api_Responses.js';
import Integration_Rules from "../../database/models/Integration_Rules.js";
import Packs_X_Packs_Origins from "../../database/models/Packs_X_Packs_Origins.js";
import Meas_X_Meas_Origins from "../../database/models/Meas_X_Meas_Origins.js";
import Midias from "../../database/models/Midias.js";


/*WINTHOR TABLE MODELS*/
import All_Tab_Columns from "../../database/models/winthor/All_Tab_Columns.js";
import PcConsum from '../../database/models/winthor/PcConsum.js';
import PcDicionarioItem from "../../database/models/winthor/PcDicionarioItem.js";
import PcDicionarioItemRot from "../../database/models/winthor/PcDicionarioItemRot.js";
import PcDicionarioItemRotCust from "../../database/models/winthor/PcDicionarioItemRotCust.js";
import PcRotulo from "../../database/models/winthor/PcRotulo.js";
import PcRotuloItem from "../../database/models/winthor/PcRotuloItem.js";
import PcPais from '../../database/models/winthor/PcPais.js';
import PcCidade from '../../database/models/winthor/PcCidade.js';
import PcCob from '../../database/models/winthor/PcCob.js';
import PcBairro from '../../database/models/winthor/PcBairro.js';
import PcFilial from '../../database/models/winthor/PcFilial.js';
import PcAtivi from '../../database/models/winthor/PcAtivi.js';
import PcRotaExp from '../../database/models/winthor/PcRotaExp.js';
import PcFornec from '../../database/models/winthor/PcFornec.js';
import PcClient from '../../database/models/winthor/PcClient.js';
import PcTabDev from '../../database/models/winthor/PcTabDev.js';
import PcVeicul from '../../database/models/winthor/PcVeicul.js';
import PcCarreg from '../../database/models/winthor/PcCarreg.js';
import PcSuperv from '../../database/models/winthor/PcSuperv.js';
import PcEmpr from '../../database/models/winthor/PcEmpr.js';
import PcUsuari from '../../database/models/winthor/PcUsuari.js';
import PcEstado from '../../database/models/winthor/PcEstado.js';
import PcDistrib from "../../database/models/winthor/PcDistrib.js";
import PcPrazo from "../../database/models/winthor/PcPrazo.js";
import PcUnidade from "../../database/models/winthor/PcUnidade.js";
import PcLinhaProd from "../../database/models/winthor/PcLinhaProd.js";
import PcNcm from '../../database/models/winthor/PcNcm.js';
import PcDepto from '../../database/models/winthor/PcDepto.js';
import PcSecao from '../../database/models/winthor/PcSecao.js';
import PcMarca from "../../database/models/winthor/PcMarca.js";
import PcCategoria from "../../database/models/winthor/PcCategoria.js";
import PcProdut from '../../database/models/winthor/PcProdut.js';
import PcProdFilial from "../../database/models/winthor/PcProdFilial.js";
import PcEst from "../../database/models/winthor/PcEst.js";
import PcEmbalagem from "../../database/models/winthor/PcEmbalagem.js";
import PcNfsaid from '../../database/models/winthor/PcNfsaid.js';
import PcPrest from '../../database/models/winthor/PcPrest.js';
import PcEstcr from '../../database/models/winthor/PcEstcr.js';
import PcDocEletronico from '../../database/models/winthor/PcDocEletronico.js';
import PcPixCobrancaDados from '../../database/models/winthor/PcPixCobrancaDados.js';
import Produtos_Armazenados_Terceiros from '../../database/models/winthor/Produtos_Armazenados_Terceiros.js';

/*WINTHOR INTEGRATION TABLE MODELS (CONTROL INTEGRATION TABLES)*/
import Error_Logs from '../../database/models/winthor_integration/Error_Logs.js'
import Integration_Tables from '../../database/models/winthor_integration/Integration_Tables.js'
import Integration_Columns from '../../database/models/winthor_integration/Integration_Columns.js'
import Integration_Control from '../../database/models/winthor_integration/Integration_Control.js'
import Integration_Parameters from '../../database/models/winthor_integration/Integration_Parameters.js'

/*SJD TABLE MODELS*/
import SjdOrigemDeDados from '../../database/models/sjd/SjdOrigemDeDados.js';
import SjdProduto_Origem from '../../database/models/sjd/SjdProduto_Origem.js';
import SjdEstoque_Origem from '../../database/models/sjd/SjdEstoque_Origem.js';
import SjdHistEst_Origem from '../../database/models/sjd/SjdHistEst_Origem.js';
import SjdTabpr_Origem from '../../database/models/sjd/SjdTabpr_Origem.js';
import SjdTabpr_Origem_Log from '../../database/models/sjd/SjdTabpr_Origem_Log.js';
import SjdLogAnaliseEnt from "../../database/models/sjd/SjdLogAnaliseEnt.js";
import XMLBroker from '../../database/models/sjd/XMLBroker.js';
import Gtin_Produtos from "../../database/models/sjd/Gtin_Produtos.js";

/*EP TABLE MODELS*/
import EpOrigensInfo from '../../database/models/ep/EpOrigensInfo.js';
import EpTrabalhadores from '../../database/models/ep/EpTrabalhadores.js';
import EpVendedores from '../../database/models/ep/EpVendedores.js';
import EpCidades from '../../database/models/ep/EpCidades.js';
import EpPessoas from '../../database/models/ep/EpPessoas.js';
import EpEmpresas from '../../database/models/ep/EpEmpresas.js';
import EpFiliais from '../../database/models/ep/EpFiliais.js';
import EpFornecedores from '../../database/models/ep/EpFornecedores.js';
import EpRotasClientes from '../../database/models/ep/EpRotasClientes.js';
import EpPracasClientes from '../../database/models/ep/EpPracasClientes.js';
import EpRedesClientes from '../../database/models/ep/EpRedesClientes.js';
import EpAtividadesClientes from '../../database/models/ep/EpAtividadesClientes.js';
import EpClientes from '../../database/models/ep/EpClientes.js';
import EpNegociosOrigem from '../../database/models/ep/EpNegociosOrigem.js';
import EpCategoriasOrigem from '../../database/models/ep/EpCategoriasOrigem.js';
import EpDeparamentosProd from '../../database/models/ep/EpDeparamentosProd.js';
import EpProdutos from '../../database/models/ep/EpProdutos.js';
import EpNfsSaida from '../../database/models/ep/EpNfsSaida.js';
import EpMovimentacoesSaida from '../../database/models/ep/EpMovimentacoesSaida.js';
import EpNfsEnt from '../../database/models/ep/EpNfsEnt.js';
import EpMovimentacoesEnt from '../../database/models/ep/EpMovimentacoesEnt.js';


/*EXTERNAL DATA TABLE MODELS (RFB)*/
import Businesses from '../../database/models/external_data/Businesses.js'
import ExternalDatasCities from '../../database/models/external_data/Cities.js'
import Cnaes from '../../database/models/external_data/Cnaes.js'
import ExternalDatasCountries from '../../database/models/external_data/Countries.js'
import Establishments from '../../database/models/external_data/Establishments.js'
import Legal_Natures from '../../database/models/external_data/Legal_Natures.js'
import Reasons from '../../database/models/external_data/Reasons.js'
import Responsible_Person_Qualifications from '../../database/models/external_data/Responsible_Person_Qualifications.js'
import Utils from "../utils/Utils.js";
import PcCodFabrica from "../../database/models/winthor/PcCodFabrica.js";
import PcRegiao from "../../database/models/winthor/PcRegiao.js";
import PcTabPr from "../../database/models/winthor/PcTabPr.js";


//console.log('END MODELSCONTROLLER IMPORTS');

export default class ModelsController {
    static async initModels(){
        //Utils.logi(this.name,'initModels');
        await Errors.initModel();
        await Logs.initModel();
        await Tables.initModel();
        await Connections.initModel();
        await Schemas.initModel();
        await Contexts.initModel();
        await Entities_Types.initModel();
        await Data_Types.initModel();
        await Action_Status.initModel();
        await Parameters.initModel();
        await Parameter_Values.initModel();
        await Data_Origins.initModel();
        await Record_Status.initModel();
        await Sync_Status.initModel();
        await Run_Status.initModel();
        await Identifier_Types.initModel();
        await Greatnesses.initModel();
        await Measurement_Units.initModel();
        await People.initModel();
        await Collaborators.initModel();
        await Access_Profiles.initModel();
        await Users.initModel();
        await User_Tokens.initModel();
        await User_Profile_Timeworks.initModel();
        await User_Timeworks.initModel();
        await Processes.initModel();
        await Routine_Types.initModel();
        await Modules.initModel();
        await Routines.initModel();
        await Routine_Contents.initModel();
        await Languages.initModel();
        await Texts.initModel();
        await Translates.initModel();
        await Relationship_Types.initModel();
        await Relationships.initModel();
        await Value_Names.initModel();
        await Relationship_Values.initModel();
        await Lists_Names.initModel();
        await Comparators.initModel();
        await Contract_Types.initModel();
        await Currencies.initModel();
        await Form_Types.initModel();
        await Financial_Value_Forms.initModel();
        await Financial_Value_Localization_Types.initModel();
        await Financial_Value_Mov_Types.initModel();
        await Continents.initModel();
        await Countries.initModel();
        await States.initModel();
        await Cities.initModel();
        await NeighborHoods.initModel();
        await Street_Types.initModel();
        await Streets.initModel();
        await Address_Types.initModel();
        await Postal_Codes.initModel();
        await Postal_Codes_Streets.initModel();
        await Postal_Codes_Paths.initModel();
        await Addresses.initModel();
        await Contact_Types.initModel();
        await Contacts.initModel();
        await People_Addresses.initModel();
        await People_Contacts.initModel();
        await Companies.initModel();
        await Business_Units.initModel();
        await Warehouses.initModel();
        await Warehouse_Address_Types.initModel();
        await Warehouse_Addresses.initModel();
        await Warehouse_Address_Coordinates.initModel();
        await Warehouse_Address_Dimensions.initModel();
        await Warehouse_Address_Capacities.initModel();
        await Clients.initModel();
        await Suppliers.initModel();
        await Collaborator_Functions.initModel();
        await Collaborator_Contracts.initModel();
        await Collaborators_X_Functions.initModel();
        await Power_Types.initModel();
        await Permissions.initModel();
        await Conditions.initModel();
        await Condition_Items.initModel();
        await Groups.initModel();
        await Groups_Items.initModel();
        await Packagings.initModel();
        await Container_Types.initModel();
        await Container_Type_Dimensions.initModel();
        await Container_Type_Capacities.initModel();
        await Gtin_Types.initModel();
        await Ncms.initModel();
        await Item_Status.initModel();
        await Items.initModel();
        await Lots.initModel();
        await Containers.initModel();
        await Items_Lots_Containers.initModel();
        await Stock_Entities.initModel();
        await Stock_Entity_Relationship_Types.initModel();
        await Item_Stocks.initModel();
        await Item_Stock_Units.initModel();
        await Item_Meas_Pack_Identif.initModel();
        await Movement_Types.initModel();
        await Movement_Status.initModel();
        await Conference_Types.initModel();
        await Movements.initModel();
        await Movement_Groups.initModel();
        await Movements_Groups.initModel();
        await Movement_Entity_Relationship_Types.initModel();
        await Movements_Entities.initModel();
        await Movs_Items_Stocks.initModel();
        await Item_Mov_Amounts.initModel();
        await Item_Mov_Units.initModel();
        await Item_Mov_Amount_Restrictions.initModel();
        await Item_Mov_Xml_Import_Id_Conversions.initModel();
        await Commission_Entitiy_Codes.initModel();
        await Commission_Items.initModel();
        await Commission_Values.initModel();
        await Objectives.initModel();
        await Sql_Object_Types.initModel();
        await Sql_Processes.initModel();
        await Report_Visions.initModel();
        await Sql_Objects.initModel();
        await Report_Data_Founts.initModel();
        await Report_Data_Fount_Items.initModel();
        await Logistic_Mov_Types.initModel();
        await Logistic_Status.initModel();
        await Logistic_Reasons.initModel();
        await Logistic_Orders.initModel();
        await Logistic_Orders_Movs.initModel();
        await Logistic_Orders_Items_Mov_Amt.initModel();
        await Logistic_Orders_Movs_Received_Values.initModel();
        await Logistic_Orders_Dest_Values.initModel();
        await Logistic_Logs.initModel();
        await Projects_Items_Types.initModel();
        await Project_Item_Origin_Types.initModel();
        await Projects_Items.initModel();
        await Requirements_Types.initModel();
        await Requirements.initModel();
        await Project_Task_Types.initModel();
        await Project_Tasks.initModel();
        await Task_Status.initModel();
        await Tasks.initModel();
        await Tasks_Status_Users.initModel();
        await Tasks_Status_Users_Logs.initModel();
        await Project_Tasks_Status_Users.initModel();
        await Campaigns.initModel();
        await Campaign_Kpis.initModel();
        await Campaign_Kpi_Value_Getters.initModel();
        await Campaign_Kpi_Value_Details.initModel();
        await Campaign_Entities.initModel();
        await Campaign_Kpi_Result_Values.initModel();        
        await Campaign_Kpi_Value_Detail_Entities.initModel();        
        await Campaign_Entities_Kpi_Value_Getters_Values.initModel();
        await Campaign_Entities_Kpi_Result_Values.initModel();
        await Apis.initModel();
        await Api_Requests.initModel();
        await Api_Request_Calls.initModel();
        await Api_Responses.initModel();
        await Maps_Api_Responses.initModel();
        await Packs_X_Packs_Origins.initModel();
        await Meas_X_Meas_Origins.initModel();
        await Midias.initModel();
        await Integration_Rules.initModel();

        if (Utils.toBool(process.env.HAS_DB_EXTERNAL_DATA) == true) {
            await Businesses.initModel();
            await ExternalDatasCities.initModel();
            await Cnaes.initModel();
            await Countries.initModel();
            await Establishments.initModel();
            await ExternalDatasCountries.initModel();
            await Legal_Natures.initModel();
            await Reasons.initModel();
            await Responsible_Person_Qualifications.initModel();
        }
        
        if (Utils.toBool(process.env.HAS_WINTHOR_INTEGRATION) == true) {
            await All_Tab_Columns.initModel();
            await PcConsum.initModel();
            await PcDicionarioItem.initModel();
            await PcDicionarioItemRot.initModel();
            await PcDicionarioItemRotCust.initModel();
            await PcRotulo.initModel();
            await PcRotuloItem.initModel();
            await PcPais.initModel();            
            await PcEstado.initModel();
            await PcCidade.initModel();
            await PcBairro.initModel();
            await PcFilial.initModel();
            await PcUsuari.initModel();
            await PcAtivi.initModel();            
            await PcCob.initModel();
            await PcRotaExp.initModel();        
            await PcRegiao.initModel();
            await PcClient.initModel();
            await PcFornec.initModel();
            await PcDistrib.initModel();
            await PcPrazo.initModel();
            await PcUnidade.initModel();
            await PcLinhaProd.initModel();
            await PcNcm.initModel();            
            await PcDepto.initModel();
            await PcSecao.initModel();            
            await PcMarca.initModel();
            await PcCategoria.initModel();            
            await PcProdut.initModel();
            await PcProdFilial.initModel();
            await PcEst.initModel();
            await PcEmbalagem.initModel();
            await PcCodFabrica.initModel();
            await PcDocEletronico.initModel();
            await PcEmpr.initModel(); 
            await PcTabPr.initModel();
            await PcNfsaid.initModel();           
            await PcPixCobrancaDados.initModel();
            await PcPrest.initModel();                       
            await PcSuperv.initModel();
            await PcTabDev.initModel();           
            await PcVeicul.initModel();
            await PcCarreg.initModel();   
            await PcEstcr.initModel(); 
            await Produtos_Armazenados_Terceiros.initModel();
            await Error_Logs.initModel();
            await Integration_Columns.initModel();
            await Integration_Control.initModel();
            await Integration_Parameters.initModel();
            await Integration_Tables.initModel();
        }

        if (Utils.toBool(process.env.HAS_CONSULT_INTEGRATION) == true) {
            await SjdOrigemDeDados.initModel();
            await SjdProduto_Origem.initModel();
            await SjdEstoque_Origem.initModel();
            await SjdHistEst_Origem.initModel();
            await SjdTabpr_Origem.initModel();
            await SjdTabpr_Origem_Log.initModel();
            await SjdLogAnaliseEnt.initModel();
            await XMLBroker.initModel();
            await await Gtin_Produtos.initModel();
        }

        if (Utils.toBool(process.env.HAS_EP_INTEGRATION) == true) {
            await EpAtividadesClientes.initModel();
            await EpCategoriasOrigem.initModel();
            await EpCidades.initModel();
            await EpClientes.initModel();
            await EpDeparamentosProd.initModel();
            await EpEmpresas.initModel();
            await EpFiliais.initModel();
            await EpFornecedores.initModel();
            await EpMovimentacoesEnt.initModel();
            await EpMovimentacoesSaida.initModel();
            await EpNegociosOrigem.initModel();
            await EpNfsEnt.initModel();
            await EpNfsSaida.initModel();
            await EpOrigensInfo.initModel();
            await EpPessoas.initModel();
            await EpPracasClientes.initModel();
            await EpProdutos.initModel();
            await EpRedesClientes.initModel();
            await EpRotasClientes.initModel();
            await EpTrabalhadores.initModel();
            await EpVendedores.initModel();
        }
        
        

        await this.initAssociations();
        //Utils.loge(this.name,'initModels');
    }

    static async initAssociations() {
        //Utils.logi(this.name,'initAssociations');
        await Errors.initAssociations();
        await Logs.initAssociations();
        await Tables.initAssociations();
        await Connections.initAssociations();
        await Schemas.initAssociations();
        await Contexts.initAssociations();
        await Entities_Types.initAssociations();
        await Data_Types.initAssociations();
        await Action_Status.initAssociations();
        await Parameters.initAssociations();
        await Parameter_Values.initAssociations();
        await Data_Origins.initAssociations();
        await Record_Status.initAssociations();
        await Sync_Status.initAssociations();
        await Run_Status.initAssociations();
        await Identifier_Types.initAssociations();
        await Greatnesses.initAssociations();
        await Measurement_Units.initAssociations();
        await People.initAssociations();
        await Collaborators.initAssociations();
        await Access_Profiles.initAssociations();
        await Users.initAssociations();
        await User_Tokens.initAssociations();
        await User_Profile_Timeworks.initAssociations();
        await User_Timeworks.initAssociations();
        await Processes.initAssociations();
        await Routine_Types.initAssociations();
        await Modules.initAssociations();
        await Routines.initAssociations();
        await Routine_Contents.initAssociations();
        await Languages.initAssociations();
        await Texts.initAssociations();
        await Translates.initAssociations();
        await Relationship_Types.initAssociations();
        await Relationships.initAssociations();
        await Value_Names.initAssociations();        
        await Relationship_Values.initAssociations();
        await Lists_Names.initAssociations();
        await Comparators.initAssociations();
        await Contract_Types.initAssociations();
        await Currencies.initAssociations();
        await Form_Types.initAssociations();
        await Financial_Value_Forms.initAssociations();
        await Financial_Value_Localization_Types.initAssociations();
        await Financial_Value_Mov_Types.initAssociations();
        await Continents.initAssociations();
        await Countries.initAssociations();
        await States.initAssociations();
        await Cities.initAssociations();
        await NeighborHoods.initAssociations();
        await Street_Types.initAssociations();
        await Streets.initAssociations();
        await Address_Types.initAssociations();
        await Postal_Codes.initAssociations();
        await Postal_Codes_Streets.initAssociations();
        await Postal_Codes_Paths.initAssociations();
        await Addresses.initAssociations();
        await Contact_Types.initAssociations();
        await Contacts.initAssociations();
        await People_Addresses.initAssociations();
        await People_Contacts.initAssociations();
        await Companies.initAssociations();
        await Business_Units.initAssociations();
        await Warehouses.initAssociations();
        await Warehouse_Address_Types.initAssociations();
        await Warehouse_Addresses.initAssociations();
        await Warehouse_Address_Coordinates.initAssociations();
        await Warehouse_Address_Dimensions.initAssociations();
        await Warehouse_Address_Capacities.initAssociations();
        await Clients.initAssociations();
        await Suppliers.initAssociations();
        await Collaborator_Functions.initAssociations();
        await Collaborator_Contracts.initAssociations();
        await Collaborators_X_Functions.initAssociations();
        await Power_Types.initAssociations();
        await Permissions.initAssociations();
        await Conditions.initAssociations();
        await Condition_Items.initAssociations();
        await Groups.initAssociations();
        await Groups_Items.initAssociations();
        await Packagings.initAssociations();
        await Container_Types.initAssociations();
        await Container_Type_Dimensions.initAssociations();
        await Container_Type_Capacities.initAssociations();
        await Gtin_Types.initAssociations();
        await Ncms.initAssociations();
        await Item_Status.initAssociations();
        await Items.initAssociations();
        await Lots.initAssociations();
        await Containers.initAssociations();
        await Items_Lots_Containers.initAssociations();
        await Stock_Entities.initAssociations();
        await Stock_Entity_Relationship_Types.initAssociations();
        await Item_Stocks.initAssociations();
        await Item_Stock_Units.initAssociations();
        await Item_Meas_Pack_Identif.initAssociations();
        await Movement_Types.initAssociations();
        await Movement_Status.initAssociations();
        await Conference_Types.initAssociations();
        await Movements.initAssociations();
        await Movement_Groups.initAssociations();
        await Movements_Groups.initAssociations();
        await Movement_Entity_Relationship_Types.initAssociations();
        await Movements_Entities.initAssociations();
        await Movs_Items_Stocks.initAssociations();
        await Item_Mov_Amounts.initAssociations();
        await Item_Mov_Units.initAssociations();
        await Item_Mov_Amount_Restrictions.initAssociations();
        await Item_Mov_Xml_Import_Id_Conversions.initAssociations();
        await Commission_Entitiy_Codes.initAssociations();
        await Commission_Items.initAssociations();
        await Commission_Values.initAssociations();
        await Objectives.initAssociations();
        await Sql_Object_Types.initAssociations();
        await Sql_Processes.initAssociations();
        await Report_Visions.initAssociations();
        await Sql_Objects.initAssociations();
        await Report_Data_Founts.initAssociations();
        await Report_Data_Fount_Items.initAssociations();
        await Logistic_Mov_Types.initAssociations();
        await Logistic_Status.initAssociations();
        await Logistic_Reasons.initAssociations();
        await Logistic_Orders.initAssociations();
        await Logistic_Orders_Movs.initAssociations();
        await Logistic_Orders_Items_Mov_Amt.initAssociations();
        await Logistic_Orders_Movs_Received_Values.initAssociations();
        await Logistic_Orders_Dest_Values.initAssociations();
        await Logistic_Logs.initAssociations();
        await Projects_Items_Types.initAssociations();
        await Project_Item_Origin_Types.initAssociations();
        await Projects_Items.initAssociations();
        await Requirements_Types.initAssociations();
        await Requirements.initAssociations();
        await Project_Task_Types.initAssociations();
        await Project_Tasks.initAssociations();
        await Task_Status.initAssociations();
        await Tasks.initAssociations();
        await Tasks_Status_Users.initAssociations();
        await Tasks_Status_Users_Logs.initAssociations();
        await Project_Tasks_Status_Users.initAssociations();
        await Campaigns.initAssociations();
        await Campaign_Kpis.initAssociations();
        await Campaign_Kpi_Value_Getters.initAssociations();
        await Campaign_Kpi_Value_Details.initAssociations();
        await Campaign_Entities.initAssociations();
        await Campaign_Kpi_Result_Values.initAssociations();        
        await Campaign_Kpi_Value_Detail_Entities.initAssociations();
        await Campaign_Entities_Kpi_Value_Getters_Values.initAssociations();
        await Campaign_Entities_Kpi_Result_Values.initAssociations();        
        await Apis.initAssociations();
        await Api_Requests.initAssociations();
        await Api_Request_Calls.initAssociations();
        await Api_Responses.initAssociations();
        await Maps_Api_Responses.initAssociations();
        await Packs_X_Packs_Origins.initAssociations();
        await Meas_X_Meas_Origins.initAssociations();
        await Midias.initAssociations();
        Integration_Rules.initAssociations();


        if (Utils.toBool(process.env.HAS_DB_EXTERNAL_DATA) == true) {
            await Businesses.initAssociations();
            await ExternalDatasCities.initAssociations();
            await Cnaes.initAssociations();
            await ExternalDatasCountries.initAssociations();
            await Establishments.initAssociations();
            await Legal_Natures.initAssociations();
            await Reasons.initAssociations();
            await Responsible_Person_Qualifications.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_WINTHOR_INTEGRATION) == true) {        
            await All_Tab_Columns.initAssociations();
            await PcConsum.initAssociations();
            await PcDicionarioItem.initAssociations();
            await PcDicionarioItemRot.initAssociations();
            await PcDicionarioItemRotCust.initAssociations();
            await PcRotulo.initAssociations();
            await PcRotuloItem.initAssociations();
            await PcPais.initAssociations();            
            await PcEstado.initAssociations();
            await PcCidade.initAssociations();
            await PcBairro.initAssociations();
            await PcFilial.initAssociations();
            await PcUsuari.initAssociations();
            await PcAtivi.initAssociations();            
            await PcCob.initAssociations();
            await PcRotaExp.initAssociations();     
            await PcRegiao.initAssociations();   
            await PcClient.initAssociations();
            await PcFornec.initAssociations();
            await PcDistrib.initAssociations();
            await PcPrazo.initAssociations();
            await PcUnidade.initAssociations();
            await PcLinhaProd.initAssociations();
            await PcNcm.initAssociations();            
            await PcDepto.initAssociations();            
            await PcSecao.initAssociations();            
            await PcMarca.initAssociations();
            await PcCategoria.initAssociations();
            await PcProdut.initAssociations();
            await PcProdFilial.initAssociations();
            await PcEst.initAssociations();
            await PcEmbalagem.initAssociations();
            await PcCodFabrica.initAssociations();
            await PcDocEletronico.initAssociations();
            await PcEmpr.initAssociations(); 
            await PcTabPr.initAssociations();
            await PcNfsaid.initAssociations();           
            await PcPixCobrancaDados.initAssociations();
            await PcPrest.initAssociations();                       
            await PcSuperv.initAssociations();
            await PcTabDev.initAssociations();           
            await PcVeicul.initAssociations();
            await PcCarreg.initAssociations();   
            await PcEstcr.initAssociations(); 
            await Produtos_Armazenados_Terceiros.initAssociations();
            await Error_Logs.initAssociations();
            await Integration_Columns.initAssociations();
            await Integration_Control.initAssociations();
            await Integration_Parameters.initAssociations();
            await Integration_Tables.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_CONSULT_INTEGRATION) == true) {
            SjdOrigemDeDados.initAssociations();
            await SjdProduto_Origem.initAssociations();
            await SjdEstoque_Origem.initAssociations();
            await SjdHistEst_Origem.initAssociations();
            await SjdTabpr_Origem.initAssociations();
            await SjdTabpr_Origem_Log.initAssociations();
            await SjdLogAnaliseEnt.initAssociations();
            await XMLBroker.initAssociations();
            await Gtin_Produtos.initAssociations();
        }

        if (Utils.toBool(process.env.HAS_EP_INTEGRATION) == true) {
            await EpAtividadesClientes.initAssociations();
            await EpCategoriasOrigem.initAssociations();
            await EpCidades.initAssociations();
            await EpClientes.initAssociations();
            await EpDeparamentosProd.initAssociations();
            await EpEmpresas.initAssociations();
            await EpFiliais.initAssociations();
            await EpFornecedores.initAssociations();
            await EpMovimentacoesEnt.initAssociations();
            await EpMovimentacoesSaida.initAssociations();
            await EpNegociosOrigem.initAssociations();
            await EpNfsEnt.initAssociations();
            await EpNfsSaida.initAssociations();
            await EpOrigensInfo.initAssociations();
            await EpPessoas.initAssociations();
            await EpPracasClientes.initAssociations();
            await EpProdutos.initAssociations();
            await EpRedesClientes.initAssociations();
            await EpRotasClientes.initAssociations();
            await EpTrabalhadores.initAssociations();
            await EpVendedores.initAssociations();
        }
        //Utils.loge(this.name,'initAssociations');
    }
}
//console.log('END MODELSCONTROLLER FILE');